"""Storage-engine dialect unit tests.

Pure-string / selection logic for :mod:`morphdb.backend` — no database
connection, so these run everywhere (including CI, which has no Postgres) and
guard the Postgres dialect translation that the engine tests can only exercise
when a live Postgres is configured.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from morphdb import backend, storage   # noqa: E402


class TestSelection(unittest.TestCase):
    def test_is_url(self):
        self.assertTrue(backend.is_url("postgresql://h/db"))
        self.assertTrue(backend.is_url("postgres://h/db"))
        self.assertTrue(backend.is_url("dynamodb://morphdb"))
        self.assertFalse(backend.is_url("/tmp/x.sqlite3"))
        self.assertFalse(backend.is_url(":memory:"))
        self.assertFalse(backend.is_url(None))

    def test_from_target_picks_engine(self):
        self.assertIsInstance(backend.from_target(":memory:"), backend.SqliteEngine)
        self.assertIsInstance(backend.from_target("/tmp/x.sqlite3"), backend.SqliteEngine)
        self.assertIsInstance(backend.from_target("postgresql://h/db"), backend.PostgresEngine)
        self.assertIsInstance(backend.from_target("dynamodb://morphdb"), backend.DynamoEngine)

    def test_from_target_none_needs_env(self):
        old = os.environ.pop("MORPHDB_DATABASE_URL", None)
        try:
            with self.assertRaises(ValueError):
                backend.from_target(None)
            os.environ["MORPHDB_DATABASE_URL"] = "postgresql://h/db"
            self.assertIsInstance(backend.from_target(None), backend.PostgresEngine)
            os.environ["MORPHDB_DATABASE_URL"] = "dynamodb://morphdb"
            self.assertIsInstance(backend.from_target(None), backend.DynamoEngine)
        finally:
            os.environ.pop("MORPHDB_DATABASE_URL", None)
            if old is not None:
                os.environ["MORPHDB_DATABASE_URL"] = old


class TestAdaptParams(unittest.TestCase):
    def test_bool_becomes_int(self):
        # MorphDB has no native boolean column; bools bind as 0/1 ints.
        self.assertEqual(backend.adapt_params([True, False, "x", 3, None]),
                         [1, 0, "x", 3, None])

    def test_empty_passthrough(self):
        self.assertEqual(backend.adapt_params(()), ())
        self.assertEqual(backend.adapt_params([]), [])


class TestSqliteDialect(unittest.TestCase):
    def setUp(self):
        self.be = backend.SqliteEngine(":memory:")

    def test_translate_is_identity(self):
        sql = "SELECT * FROM t WHERE a=? AND b=?"
        self.assertEqual(self.be.translate(sql), sql)

    def test_like_ci(self):
        self.assertEqual(self.be.like_ci(), "LIKE")

    def test_describe(self):
        self.assertEqual(self.be.describe(), ":memory:")


class TestPostgresDialect(unittest.TestCase):
    def setUp(self):
        self.be = backend.PostgresEngine("postgresql://user:secret@host:5432/db")

    def test_placeholders(self):
        self.assertEqual(self.be.translate("SELECT * FROM t WHERE a=? AND b=?"),
                         "SELECT * FROM t WHERE a=%s AND b=%s")

    def test_insert_or_ignore_becomes_on_conflict(self):
        self.assertEqual(
            self.be.translate("INSERT OR IGNORE INTO t (a, b) VALUES (?, ?)"),
            "INSERT INTO t (a, b) VALUES (%s, %s) ON CONFLICT DO NOTHING")

    def test_literal_percent_is_escaped(self):
        # psycopg treats the query as a format string when params are passed,
        # so a literal % must be doubled.
        self.assertEqual(self.be.translate("SELECT '50%' WHERE a=?"),
                         "SELECT '50%%' WHERE a=%s")

    def test_like_ci(self):
        self.assertEqual(self.be.like_ci(), "ILIKE")

    def test_describe_masks_credentials(self):
        d = self.be.describe()
        self.assertNotIn("secret", d)
        self.assertIn("host:5432/db", d)

    def test_ddl_autoincrement_rewrite(self):
        ddl = self.be._ddl("id INTEGER PRIMARY KEY AUTOINCREMENT, x TEXT")
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", ddl)
        self.assertNotIn("AUTOINCREMENT", ddl)


class TestDynamoDialect(unittest.TestCase):
    def test_describe_is_credential_free(self):
        be = backend.DynamoEngine(
            "dynamodb://morphdb?region=us-west-2&endpoint_url=http%3A%2F%2Flocalhost%3A8000")
        self.assertEqual(
            be.describe(),
            "dynamodb://morphdb?region=us-west-2&endpoint_url=http://localhost:8000")

    def test_create_table_flag(self):
        be = backend.DynamoEngine("dynamodb://morphdb?create_table=true")
        self.assertTrue(be.create_table_flag)

    def test_missing_table_name_rejected(self):
        with self.assertRaises(ValueError):
            backend.DynamoEngine("dynamodb://")


class TestInterface(unittest.TestCase):
    def test_engines_satisfy_the_interface(self):
        self.assertIsInstance(backend.SqliteEngine(":memory:"), backend.DatabaseEngine)
        self.assertIsInstance(backend.PostgresEngine("postgresql://h/db"),
                              backend.DatabaseEngine)
        self.assertIsInstance(backend.DynamoEngine("dynamodb://morphdb"),
                              backend.DatabaseEngine)

    def test_old_backend_names_remain_aliases(self):
        self.assertIs(backend.Backend, backend.DatabaseEngine)
        self.assertIs(backend.SqliteBackend, backend.SqliteEngine)
        self.assertIs(backend.PostgresBackend, backend.PostgresEngine)
        self.assertIs(backend.DynamoBackend, backend.DynamoEngine)

    def test_old_storage_names_remain_aliases(self):
        self.assertIs(storage.SqlStorage, storage.SqlStore)
        self.assertIs(storage.DynamoStorage, storage.DynamoStore)

    def test_abstract_base_cannot_be_instantiated(self):
        with self.assertRaises(TypeError):
            backend.DatabaseEngine()

    def test_no_abstract_methods_left_unimplemented(self):
        # If an engine forgot a method, instantiation raises TypeError; these
        # succeed only because both implement the full contract.
        self.assertEqual(backend.SqliteEngine(":memory:").__abstractmethods__,
                         frozenset())
        self.assertEqual(backend.PostgresEngine("postgresql://h/db").__abstractmethods__,
                         frozenset())
        self.assertEqual(backend.DynamoEngine("dynamodb://morphdb").__abstractmethods__,
                         frozenset())


if __name__ == "__main__":
    unittest.main()
